---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: eventmesh-backend
  namespace: knative-eventing
  labels:
    app.kubernetes.io/version: devel
    app.kubernetes.io/component: eventmesh-backend
