---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eventmesh-backend
  labels:
    app.kubernetes.io/version: devel
    app.kubernetes.io/component: eventmesh-backend
subjects:
  - kind: ServiceAccount
    name: eventmesh-backend
    namespace: knative-eventing
roleRef:
  kind: ClusterRole
  name: eventmesh-backend
  apiGroup: rbac.authorization.k8s.io
